FROM node:16.17-buster-slim
# from https://hub.docker.com/_/node/   Debian Buster slim Node 16.17 LTS (from .13)

ARG VERSION=3.9.13

RUN apt-get update && apt-get install -y make build-essential libssl-dev libncurses5-dev \
    libncursesw5-dev zlib1g-dev libnss3-dev libgdbm-dev libsqlite3-dev libffi-dev libreadline-dev \
    xz-utils tk-dev liblzma-dev libbz2-dev python-openssl git curl   wget llvm awscli findutils jq

# RUN echo "deb-src http://archive.ubuntu.com/ubuntu/ buster main" >> /etc/apt/sources.list

RUN npm config set fund false
RUN npm install -g npm@8.15.1 && npm install -g serverless
# Install serverless v3 globally

# Install python3 VERSION from source
RUN wget https://www.python.org/ftp/python/$VERSION/Python-$VERSION.tgz && tar xzf Python-$VERSION.tgz && rm Python-$VERSION.tgz
WORKDIR Python-${VERSION}
RUN ./configure --enable-optimizations && \
    make altinstall && \
    ls /usr/local/bin/python*
RUN update-alternatives --install /usr/bin/python3 python3 /usr/local/bin/python3.9 1 && \
    /usr/local/bin/python3.9 -m pip install --upgrade pip  &&  \
    update-alternatives --install /usr/bin/pip3 pip3 /usr/local/bin/pip3.9 1 && \
    pip3 install --upgrade pip && \
    pip3 install virtualenv==20.12.1 pipenv==2022.8.5 yq
# pin version due to incompatibilities with current dependency setup

RUN npm --version && python3 -V && pip3 -V && python -V && pip -V && pip3 freeze
## TODO put them in lable

CMD ["sh"]