version: "3"
services:
  web:
    image: nginx:1.22.1
    ports:
      - "8888:8888"
    volumes:
      - "/home/agoitia/curso_docker/docker_exercises/lesson_4/ex1.conf:/etc/nginx/nginx.conf"
      - "/home/agoitia/curso_docker/docker_exercises/lesson_4/src/ex1_web.html:/var/www/index.html"
