services:
  example:
    image: python:slim-buster
    container_name: compose2_example
    environment:
      FOO: 'BAR'
    entrypoint: ""
    working_dir: /opt/app
    command: "python example.py"
    volumes:
      - ./src:/opt/app


# run with docker compose up -d example
